<?php

namespace ConradCaine\ShameBoardBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ShameRuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShameRuleRepository extends EntityRepository
{
}
