<?php

namespace ConradCaine\ShameBoardBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VoteTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteTokenRepository extends EntityRepository
{
}
