<?php

namespace ConradCaine\ShameBoardBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ShameVoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShameVoteRepository extends EntityRepository
{
}
