<?php

namespace ConradCaine\ShameBoardBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ShameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShameRepository extends EntityRepository
{
}
